### ISSUE TITLE
Move all DNS records to Amazon Route 53

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#2]
Route 53 allows for programmatically setting DNS records, which is useful for setting up new servers, as well as load-balancing and scalable swarm setups.

Current DNS provider is not sufficient anymore, so we need to move all records over to R53.
## todo
- [x] move `mapic.io` to Route 53
- [x] create script for creating new DNS entries
- [x] move all other domains to Route 53 also
- [x] create script for registering a new domain
- [x] [simplify](http://nginx.org/en/docs/http/server_names.html) nginx config
