### ISSUE TITLE
Mapic Cli (cleanup)

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#27]
Create a wrapper for scripts in `mapic` namespace. Central place for maintenance of scripts and ENV. 

### Todo
- [x] Refactor so that `mapic/mapic` == cli. See https://github.com/mapic/mapic/issues/37
- [x] Make it possible to use SDK without downloading entire mapic.
- [x] Init Mapic install with oneliner (`wget -qO- https://get.mapic.io/ | sh`). Install starts here. (`t1.micro` webserver from container, serving latest script from mapic/mapic [repo script](https://github.com/mapic/mapic/blob/master/cli/get.mapic.io.sh)). 
- [x] Self-register and -install, with prompt for first ENVs. 
- [x] Install everything with `mapic install mapic`, incl. all config settings.
- [x] Travis build with `mapic travis`
- [ ] Start hardware nodes by simple `mapic deploy [options]`
- [ ] Make all scripts run in docker container, removing dependency on nodejs, using docker image instead etc.
- [x] `mapic status`: status printing running containers, building npm modules, ready, if expected containers are down, size of things, available hardware, users, etc.
- [x] `mapic logs`: use docker log files directly ([link](https://stackoverflow.com/questions/41144589/how-to-redirect-docker-logs-to-a-single-file))

#### Installing
- [ ] clean up sudo requirements on mapic-cli install (and prompt properly)
- [ ] make mapic run without `sudo`
- [ ] don't install sed with sudo to remove this warning: `sed: couldn't open temporary file /usr/local/bin/sedp43Tpy: Permission denied`
- [ ] `get.mapic.io`: fix SSL with static s3 website (https://knightlab.northwestern.edu/2015/05/21/implementing-ssl-on-amazon-s3-static-websites/)
- [ ] `Support for Windows in CLI` Should be easy, since everything else is supported, just need to fix a few hotspots in the cli.

#### ENV/config
- [x] Same-state between `mapic` ENV and configs of all parts. Good time to clean up all configs.
- [x] `mapic config` to show config. 
- [x] move config files to default folder, user never touches these.
- [x] move all `mapic env` commands to `mapic config`
- [x] differentiate between `mapic config` and `mapic config api` (somehow)
- [ ] ensure clean install even if previous `.mapic.env` exists
- [x] make sure previous env (like aws keys) are not lost if installing anew.
- [x] move all `mile` configs to ENV (very few, and it's cleaner)
- [x] concat redis confs
- [ ] fix mongo config, remove start.sh script, deprecated auth
- [ ] remove `env.sh` file for postgis, put somewhere else

# CLI
### Management
- [x] `mapic start`  
- [x] `mapic stop `
- [x] `mapic restart `
- [x] `mapic logs`
- [x] `mapic status`
- [x] `mapic test`
- [x] `mapic ps`
- [x] `mapic enter`

### Install
- [x] `mapic install stable [domain]`
- [x] `mapic install docker`
- [x] `mapic config` ->` .mapic.env` and all config goes here

### SDK / API
SDK for end-users who wants to upload data from terminal or script. Self-configuring, with one-liners: `mapic upload BIG.TIFF`, `mapic create user`, `mapic download [uuid] [--format shp]`.

- [x] `mapic user list`
- [x] `mapic user create`
- [x] `mapic user super`
- [x] `mapic upload` 
- [x] etc.. perhaps without `api` name, just `mapic upload`.
- [ ] also to be used for scripting, eg. `PROJECT_ID=$(mapic create project)`.

### Info
- [x] Script checks `$MAPIC_DOMAIN` env, prompts user. Also self-configuring with email, and other things needed. 
- [x] `$MAPIC_ROOT_FOLDER` becomes the directory/mapic `curl` was run in.
- [x] All ENVs will be contained in a file which is sourced on each `mapic-cli` run, so that mapic keeps an internal store of ENV, not dependent on host.
- [x] Script is automatically symlinked, eg. `ln -s /mapic/scripts/cli/mapic-cli.sh /usr/bin/mapic`.

**Comment by knutole** [comment]
First simple script created, with ticked commands above.

**Comment by knutole** [comment]
## Cleanup todo

- [ ] Install with minimal deps
- [ ] Install deps as needed
- [ ] Don't join swarm on install
- [ ] join swarm as needed
- [ ] kill nginx service as needed
- [ ] dont create dns if not needed (prompt).. some DNS are external
- [ ] label nodes automatically, eg. `mile=true`
- [ ] create new user with new creds, delete default user
- [ ] create default project 
- [ ] test clean up: deleted users (`undefined undefined`)
