### ISSUE TITLE
Public user created multiple times

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#28]
The user `2   public      Mapic             Public     public@mapic.io     59216c3222c4ff00234ccd6c` is being created many times. 

### todo
- [x] stop creationg from happening, and 
- [x] refuse to create user on existing username and email.
- [x] clean up mocha test projects/users etc at the same time
