### ISSUE TITLE
Scaling working document

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#36]
Copied from [Scaling Project Scope](https://github.com/mapic/mapic/wiki/Scaling-Project-Scope/971d3d94f7232061136e01bc596946b76578c7f2).

### Goal: 
Scale raster tile processing across 3 nodes.

### Entails:
- [x] Utilize more nodes (=servers/hardware) to host `mile` and `postgis` containers.
- [x]  Make containers standalone and agnostic.
- [x] Load-balancer which redirects tile requests to one of several `mile` containers. (`nginx -> load-balancer -> mile`)
- [x] Internal addressing for available containers (mile, postgis, redis).
- [x] Handling of `access_tokens` across nodes.
- [x] Refactoring of data flow.
- [ ] Replicating `postgis` containers (ie. with sync). (This will likely create unforeseen sync problems.) [Example.](https://gist.github.com/volkanunsal/ad2173e2649393fcd3b6) Need to benchmark first to understand potential gains
- [x] Deploy with replicated nodes. (Adding/removing containers to running server is post-MVP.)
- [ ] 1-3 `postgis`
- [x] 1-3 `mile` nodes. 
- [x] 1 node to host the rest (Redis, Mongo, Engine).
- [x] Orchestrated with Docker Swarm mode and overlay networks.
    - [x] `Master (node 1)`: Engine, webserver, mongo, redis, PostGIS (for importing data)
    - [x] `Slaves (nodes 2-4)`: Mile, redis-layers-replicas
    - [ ] `Slaves (nodes 2-4)`: PostGIS-replicas (for exporting data)
- [x] Result: 3 x 12 cpu = 36 parallell threads processing raster tiles. 
- [x] Automatic service discovery, allowing spinning containers up and down at will.
- [x] Automate tile creation. Processing all zoom levels on request. 
- [x] MVP does not mean bugfree or optimized. 

### Schematic
What the server/docker infrastructure will look like in MVP:
![server-infrasctructure](https://cloud.githubusercontent.com/assets/2197944/26045359/1e1b2364-394a-11e7-90c4-6a8bc2c00848.png)

> _Notes to schematic:_
> - _Some connections are not shown, for example `mile` connections to redis/mongo/engine._
> - _PostGIS containers in `nodes 2-4` replicate with "master" PostGIS on `node 1`._
> - _PostGIS on `node 1` is for `importing` only. PostGIS on `nodes 2-4` are for `exporting` data only._
> - _Redis containers will probably be present on `nodes 2-4` as well, replicating with `node 1`._
> - _"Load-balancer" will probably be a standalone NodeJS proxy with knowledge of available resources._
> 

## Outside scope
These points are NOT part of the MVP scope. They are listed here only for future reference.
- [x] Refactoring of databases (redis, mongo). Make all processes talk to one API. 
- [x] Refactoring of `mile` connections to redis/mongo/api.
- [ ] Explore parallell reading from PostGIS (?). Currently reading with one thread. 
- [ ] Scheduling of tile processing when there's availability. 
- [ ] Load-balancing based on availability instead of random/even. Weight calc based on current workload (number * size), and available cpu's on containers - for both `postgis` and `mile`.
- [ ] Stability improvements, optimizations.

**Comment by knutole** [comment]
## Phase 1
- [ ] replicate `mile` containers, talk to single `postgis`
- [ ] one manager node with full normal setup + one worker node with `mile` 
- [ ] test nginx load-balancing 

## Phase 2
- [ ] replicate postgis with sync across two nodes

**Comment by knutole** [comment]
#### todo
- [ ] ensure all is taken care of with `mapic configure`, incl. dns, ssl
- [ ] not possible to refresh mongo auth on db that's already in use? 
- [ ] same for redis? if so - don't refresh these auths, only when creating volume. if not, find way to do this every time...
- [ ] move on, config will change later anyway..
- [ ] otherwise, it's working on one node
- [ ] next: move mile to worker-node

**Comment by knutole** [comment]
- [ ] how to have secure / private data on same swarm.. different domains on same swarm.. it's a matter of separate postgis/engine/nginx/redis on one node, and mile on others... 
- [ ] mile: cached tiles, where are they stored replicated? 
- [ ] simplify: redis + redis-kue
- [ ] `mapic test quick`
- [ ] `mapic test mile` should get access details from ENV, not access.ignore.json
- [ ] how to orchestrate several mapic domains from same server and with `mapic` cli... perhaps to run `mapic configure` "manually" from node (which needs to be co-manager) while connecting to swarm. 
- [ ] add all init installation of new server to mapic cli (install fish, htop, rsub etc)
- [ ] run tor relay automatically as part of mapic, one on every node `mapic tor status`. verify tor md5 when installing. use mapic/tor:latest. push to docker hub. clean up readme. 
- [ ] run localhost as manager, in addition to managers on aws
- [ ] write benchmarks, tests

**Comment by knutole** [comment]
## rendered tiles  
- [x] Needs to sync between `mile` nodes, so that they can find shared cache  
- [x] Perhaps better to save the rendered tiles to disk somewhere central - like S3? Or at least a centralized node? Is S3 fast enough? It should be...
- [x] save tiles to s3

## postgis
- [ ] as for postgis, perhaps it's better to use AWS after all... 

## docker
- [ ] should remove all persistent data from docker altogether, making them simple state-less containers for running code
- [ ] move mile data (tiles, grids) to AWS S3
- [ ] move postgis data (geodata) to AWS RDS
- [ ] move mongo data (users, layers, projects) to AWS
- [ ] move redis data (layers) to AWS
