### ISSUE TITLE
Refactor repos

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#37]
## Refactor repos
`mapic/mapic` will become the repo for `mapic-cli`, where all scripts and default configs are contained and containers linked together. Everything else will be contained in separate repos. 

All config will be moved to ENV file with mapic-cli. actual configs will be created dynamically and never touched manually. in other words, no need for a config repo for each portal, simply a single `.mapic.env` file.

### Todo
- [x] clean up mapic/mapic and cli repo
- [x] remove all config repos
- [x] move all docker builds to standalone repos, compatible with docker pull. 
    - [x] https://github.com/mapic/docker-mapic-nginx
    - [x] etc
- [x] automated docker builds https://hub.docker.com/u/mapic/
- [x] travis for docker builds https://travis-ci.org/mapic
- [x] all issues in `mapic/mapic` 
- [x]  ~~fix osx build on travis (install docker manually) (docker not supported on travis/osx)~~
- [x] update tests on engine/mile/mapic.js and add `mapic test all` to mapic/mapic travis build
- [ ] move phantomjs and graphicsmagick to standalone containers, build mapic/geo without it
- [ ] does mapic/engine need mapnik? clean up image bases, no reason for mile and engine to run on similar bloated image

##### Docker Hub Automated builds
Because the layers are completely new, Docker’s build robot pushes all new layers when it pushes the built image back to Docker Hub, slowing the Automated Build down even more (the familiar "image layer already exists, skipping" message is nowhere to be found).
When end users go to docker pull the image built using an Automated Build, they always get new layers even if they have pulled that same image before. This means that even if you only changed one character in one line of source code, you will most likely have to pull down anywhere from 80 megabytes to a gigabyte or more of Docker image layers. This makes Automated Builds look very unattractive for real production deployments.

aka **DONT USE DOCKER HUB AUTOMATED BUILDS**

**Comment by knutole** [comment]
## geo image refactor
- buidling on mapic/docker-mapnik3 (deb/jessie)
- all is jessie
- installed postgis, gdal
- removed graphicsmagick and phantomjs (not fixed in code)
- should create standalone images and containers for gm/phjs 
- todo: build and test with mapic/engine etc, probably still something missing
