### ISSUE TITLE
M.Layer.Graph

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#56]
### Goal
The goal of the project is to visualize data related to a given geographical area (mask), within the Mapic web-portal. The user should be able to upload a simple `GeoJSON` mask, and append `CSV` data to the layer. This data will the be automatically represented in simple charts when the layer is activated.

### Details
- [x] A new, separate layer type will be implemented: `M.Layer.Graphs`
- [x] The `M.Layer.Graphs` layer type can contain any number of CSV data sets
- [x] The CSV data sets will be automatically detected and visualized in a graph chart 
- [ ] ~~Each CSV data set can contain multiple colums of values, which will be represented as separate functions in the chart~~
- [x] The user can decide the Y-axis range of the chart manually, or have it detected automatically
- [x] The X-axis will always represent one year, starting in January
- [x] The titles of the Y-axis and graph functions will be determined from the CSV directly
- [x] The graph functions in each CSV data set can be clicked on/off in the graph

### Images
Example of GeoJSON mask:  

<img width="481" alt="screen shot 2017-11-09 at 09 54 38" src="https://user-images.githubusercontent.com/2197944/32596559-07cd552a-c534-11e7-9031-8ea933317cdd.png">

Example of graph chart:  

<img width="644" alt="screen shot 2017-11-09 at 09 55 20" src="https://user-images.githubusercontent.com/2197944/32596589-2209e6d8-c534-11e7-85a9-ee5ad81c8f40.png">

**Comment by knutole** [comment]
## Todo
- [ ] validate geojson

**Comment by knutole** [comment]
- [ ] forskjellige grafer ligger over hverandre
- [ ] metadata error msg
- [ ] graf blir ikke borte når velger bort laget 
- [ ] desimaler i y aksen mangler
- [ ] gjøre boksen mindre/større (canvas)
- [ ] gjør "draw" setting off by default


![screen shot 2017-11-24 at 12 26 11](https://user-images.githubusercontent.com/2197944/33208658-ae602fea-d112-11e7-932a-5fef9423b91c.png)
- [ ] diff from year / diff from average

**Comment by knutole** [comment]
done
