### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#59]
## bugs
- [ ] when switching between SCF projects, the second projects hangs. symptoms: 
- [ ] Chrome only: dragging map when dragging opacity on info box. (NB! Not an issue on Safari, so this is due to Chrome's ever-changing handling of pointer-events and click-throughs.)
- [ ] Satellite angle on info box is "hanging" when switching layers, ie. it doesn't disappear when it should.

## feature request
- [ ] "hardcoded" geotiff map legend, ability to display different min/max, text, (and later, presumably, color scale).

**Comment by knutole** [comment]
`SCF_MOD_20180713_140132.tif`
`mask-rjukan.scf.json`

## Changes
Need to make updates to the chart in terms of what data is showing. Hydrological years are from 1. sept to 31. august, and we're in a new year now. That means very little raster data will be displayed, only the last few days since Sept 1st. This is good. 

When it comes to the datasets which are displayed in the graph, the latest hydrological year (ie. 2018-2019) should be displayed, which will create a very short line for now. In other words, little data will be available for the current h-year. This is fine.

### todo
- [ ] years should be called `2017-2018`, `2018-2019`, etc.
- [ ] SCF rasters should be displayed for the current h-year only
- [ ] projects should be created empty, with only a plugin for ftp or http. all data should then be downloaded from the ftp/http and filled into the project. this is much cleaner than initial upload + automatick update. 
- [ ] projects should be created in the UI, with mask that can be uploaded and defined
- [ ] ensure `pre-render` still works

- years should be called 2017-2018, 
- dont show scf data for the past year, only starting from 1. sept the current year
- only 

- todo: set up a project for them with CLI
- feature: create UI for creating SCF projects 
- bug: limit the number of years selected in graph
