### ISSUE TITLE
Updates to Snow Cover Fraction Layer type

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#60]
## Changes
We need to make updates to the chart in terms of what data is showing. @franocetinic has proposed a clean solution:
- Hydrological years are from 1. sept to 31. august. We're in a new year now, which means that very little raster data will be displayed, only the last few days since 1. sept. 
- When it comes to the data which is displayed in the graph, the latest hydrological year (ie. 2018-2019) should be displayed, which will create a very short graph line when early in the h-year. 
- To create a SCF project, one should simply need to make an empty project and add a SCF type layer to it using UI or API.
- Additional `mask data` and `raster datasets` should be added using the Mapic Web API. The API can be accessed using by using the Mapic CLI bash library, which can be called from a bash script or cronjob, like this: 
```bash
# add another scf raster
mapic api layer update --layer-id layer_id --add-dataset /tmp/SCF_MOD_01012018.tif

# update mask data
mapic api layer mask update --layer-id layer_id --mask-id mask_id --mask-json /tmp/mask.scf.json 

```

## Todo
- [x] Years should be called `2017-2018`, `2018-2019`, etc.
- [x] SCF rasters should be displayed for the current h-year only
- [x] test/calibrate graph with test-data to ensure correct display of all data points and dates
- [x] The SCF layers should be created empty. Layers should be filled with masks and datasets through the API.
- [x] Create API for managing SCF layers
- [x] Add API functions to Mapic CLI
    - [x] layer create
    - [x] layer create (mask)
    - [x] project create
    - [x] layer update
    - [x] layer update (mask)
    - [x] layer update (dataset)
- [x] Cleanup CLI
    - [x] check variables on `mask update`, ie. if only json can be added without overwriting other vars
- [x] Ensure `pre-render` still works 
    - [x] for both InSAR
    - [x] and SCF-layers
- [x] Update test coverage
    - [x] mask discreet update
- [ ] Create UI for creating SCF layers
- [ ] Move UI  (+) button to top
- [x] Write documentation for the SCF layer type.
- [x] Update portals with latest code
- [x] Bump version and changelog => `18.09`
- [x] create POST endpoint for access token

#### bugs
- [x] fix UI overflow bug when > 7 years of data in the scf graph list
- [x] remove timeseries raster datasets in `Data` pane to make the list more manageable
- [ ] when switching between SCF projects, the snow graph hangs up
- [x] new hydrological year messes with dates (again) in SCF project, since we're after sept. 1st
- [x] remove styling slider (appears on raster after adding values)
- [x] min/max/avg yearly data in graph is not plugged in
- [x] h-year starts on sept 2nd, should be sept 1st

#### additional features
- [x] `flyTo` in layermenu on SCF layers should focus on the mask layer

**Comment by knutole** [comment]
```bash
# create project
mapic api project create \
    --project_name project_name \
    --private

# create scf-layer and add to project
mapic api layer create scf \
    --add_to_project project_id

# add mask to scf-layer
mapic api layer create mask \
    --layer_id layer_id \
    --mask_geojson /tmp/mask.geojson \
    --mask_json /tmp/mask.scf.json \ 
    --mask_title mask_title \
    --mask_description mask_description \
    --mask_meta "område=hallingdal" \
    --mask_meta "kraftverk=mår"

# update daily mask data 
mapic api layer update \
    --mask_id mask_id \ 
    --layer_id layer_id \
    --mask_json /tmp/mask.scf.json

# add daily raster to scf-layer
mapic api layer update \
    --layer_id layer_id \
    --add_dataset /tmp/SCF_MOD_01012018.tif








```

**Comment by knutole** [comment]
## Example script 3: Update daily mask data

This script updates the mask data, ie. the data that goes into the SCF graph. The variables below must be filled in with ID's from Example Script 1, and the `MASK_DATA_JSON_ABSOLUTE_PATH` must be an absolute path to the latest version of the mask data.

This script could also be run as a cronjob with slight modifications.

```bash
#!/bin/bash

MAPIC_LAYER_ID=cube-faa8957e-f225-4e78-b454-2bc36b01b679
MAPIC_MASK_ID=mask-uaquhqsd
MASK_DATA_JSON_ABSOLUTE_PATH=/home/ubuntu/mapic/cli/tmp/mask.calibration.json

# update mask with geometry and title and daily data
echo "Updating mask with geometry and data..." 
mapic api layer mask update \
    --mask-id $MAPIC_MASK_ID \
    --layer-id $MAPIC_LAYER_ID \
    --mask-json $MASK_DATA_JSON_ABSOLUTE_PATH

```

**Comment by knutole** [comment]
## REST API

### Get `access_token` from email/password
```js
api.get('/v2/users/token')
.query({
    username : EMAIL
    password : PASSWORD
})
.send()
.end(function (err, res) {
    if (!res || !res.text) return done('Failed to connect to Mapic API.');
    var tokens = utils.parse(res.text);

    // access_token used for requests
    var access_token = tokens.access_token;
});
```

**Comment by knutole** [comment]
## REST API: Update daily raster to SCF layer

### Upload dataset to API and add to layer
```js
// needed to store vars between functions
var tmp = {}; 
```

```js

// step 1: upload dataset to API

const ACCESS_TOKEN = '';
const DATASET_PATH = '';

api.post('/v2/data/import')
.type('form')
.field('access_token', ACCESS_TOKEN)
.field('data', fs.createReadStream(DATASET_PATH))
.end(function (err, res) {
    if (err) return console.log(err);
    var dataset = res.body; 
    tmp.dataset = dataset;
});
```

```js 
// step 2: add dataset to layer

var data = {
    access_token : ACCESS_TOKEN,
    cube_id :  LAYER_ID, // from previous step
    datasets : [{
        id : tmp.dataset.file_id,
        description : tmp.dataset.filename,
        timestamp : parse_date_YYYYMMDD(tmp.dataset.filename)
    }]
}

api.post('/v2/cubes/add')
.send(data)
.end(function (err, res) {
    if (err) return done(err);
    var cube = res.body;
    debug && console.log(cube);
    done && done(err, cube);
});

// helper functions for date parsing
function parse_date(f) {
    var d = dataset.options.dateformat;
    if (d == "YYYYMMDD") return parse_date_YYYYMMDD(f);
    if (d == "YYYYDDD") return parse_date_YYYY_DDD(f);
}

// helper functions
function parse_date_YYYY_DDD(f) {
    // f is eg. "SCF_MOD_2014_002.tif"
    var a = f.split('.');
    var b = a[0].split('_');
    var year = b[2];
    var day = b[3];
    var yd = year + '-' + day;
    var date = moment.utc(yd, "YYYY-DDDD").format();
    return date;
}

function parse_date_YYYYMMDD(f) {
    // f is eg. "SCF_MOD_20150101.tif"
    var a = f.split('.');
    var b = a[0].split('_').reverse();
    var dato = b[0];
    var date = moment.utc(dato, "YYYYMMDD").format();
    return date;
}

```
