### ISSUE TITLE
Q4 Roadmap

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#68]
## Snow Cover Data Source
_Get SCF statistics data from an external API. Separate JSON into backdrop (avg/min/max) and yearly data._

#### SCF Data
- [ ] backdrop data (aka avg/min/max data) from external endpoint URL
- [ ] historical yearly data (incl. current year) from external endpoint URL 
- [ ] add JSON ID for requesting the data
- [ ] request the data on project load, and parse
- [ ] request data only when needed (eg. when clicking historical year)
- [ ] refactor parsing of JSON data
- [ ] refactor request flow for cube dataset
- [ ] update tests

`Estimated: 20h`

## Layer functionality
_Control draw order of layers. Toggle `scf-graph`, and add minimal slider._

#### Draw order
- [ ] Possibility to control draw order of layers
- [ ] Refactor layermenu and z-indexing
- [ ] Centralize draw order of all layers
- [ ] Create GUI for draw order

`Estimated: 20h`

#### SCF Graph
- [ ] Toggle `scf-graph` in Data tab (for editors only)
- [ ] Add standalone slider for `scf-graph`, to be shown only when `scf-graph` is hidden

`Estimated: 5h`

## WMS Layers
_Use WMS layers._
- [ ] Create layer with (+) button in Data tab
- [ ] Fully customizable WMS URL
- [ ] Legend as `.png` from external endpoint url
- [ ] Legend box with pulled `.png`

`Estimated: 10h`

## GeoJSON Layers
_Use GeoJSON layers._
- [ ] Create layer with (+) button in Data tab
- [ ] Import GeoJSON from URL
- [ ] Import GeoJSON styling string from URL
- [ ] Save styling on Layer after `GET` 
- [ ] Use data from `properties.popup` for onClick popup content
- [ ] Legend as `.png` from external endpoint url
- [ ] Legend box with pulled `.png`

`Estimated: 10h`

## Other GUI changes
_Cleanup, features._

#### Cosmetics
- [ ] Remove Data, Style, Options tabs in "Viewer" mode
- [ ] Set GUI color to specific hex

`Estimated: 2h`

#### SCF Header
- [ ] Add title box for SCF date at top of page

`Estimated: 1h`

#### SCF masks styling
- [ ] Possibility to edit styling of SCF masks
- [ ] GUI for editing
- [ ] Refactor layer mask styling
- [ ] Save styling to cube layer

`Estimated: 5h`

#### SCF Legends
- [ ] SCF legends reflect color of actual SCF raster styling
- [ ] Refactor legends in Styler
- [ ] Create gradient from styling
- [ ] Save to layer

`Estimated: 10h`
