### ISSUE TITLE
Roadmap draft

### ISSUE THREAD

**Issue by knutole** [mapic/mapic#8]
## Vector tiles (VT)
Implement vector tiles as primary data source, giving greater control of data content and styling, as well as solving some challenges in terms of styling at different zoom levels and pre-processing of data.

#### Server-side
- [ ] Serving vector tiles from PostGIS on demand
- [ ] Pre-render of vector tileset on import
- [ ] Serving raster tiles from vector tileset + stylesheet
- [ ] Options to tune simplification of VT across zoom levels
- [ ] Options to define columns in VT tile set for simplification
- [ ] VT for both pixel-data and points (combining polygons; filtering out points)  

#### Client-side
- [ ] [Mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) for reading vector tiles in client
- [ ] Interchangable mapping backend ([LeafletJS](http://leafletjs.com/),  [Mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js), [CesiumJS](https://cesiumjs.org/))
- [ ] Plugins for interacting with vector tile data
- [ ] Styler for changing style of VT data based on content
- [ ] Point- and polygon support
- [ ] Simple query tools interacting with VT

## Scalability
Build a scalable architecture where the portal can run on any number of nodes, giving greater processing power and increased redundancy. This includes catering for running the portal in the cloud, on a local cloud, or a combination of both.

- [ ] Docker Swarm architecture on AWS (or any cluster)
- [ ] Multiple nodes for `PostGIS` and `Mile` containers
- [ ] Redundant `ID` endpoints.
- [ ] Load balancer

## Data sources
Support for different datasources, including special raster formats, as well as databases and WMS. This includes support for a list of output formats.

#### Raster
- [ ] GeoTIFF `float32` support for `pgraster` _should_ in fact be possible ([pgraster](https://github.com/mapnik/mapnik/blob/master/plugins/input/pgraster/TODO))
- [ ] Support for several bands in GeoTIFF
- [ ] Support for other raster formats, eg. `ECW`, `JPEG2000`.

#### Vector
- [ ] Support for `.kmz / .kml` formats

#### Remote sources
- [ ] Inclusion of other datasources from WMS services
- [ ] Querying of WMS datasources
- [ ] Pull data from ArcGIS Geodatabase
- [ ] Pull from Orcale Spatial database
- [ ] Plugin button in ArcGIS, QGIS for importing data directly to Mapic 
- [ ] Increased support for Mapbox, Carto layers

#### Output formats
- [ ] Data available as `vector tiles`, `raster tiles`
- [ ] Downloads available as `GeoTIFF`, `Shapefile`, `GeoJSON`, `TopoJSON`, etc.

## 3D
Fully support a 3D environment for maps and data, yielding possibility of viewing data in the context of a DEM. This includes VR support out of the box. Also possibility of viewing data content in the `z` dimension, ie. seeing `mvel` as height as well as color on a point.

- [ ] [CesiumJS](https://cesiumjs.org/) 3D library in client
- [ ] Support for [3Dtiles](https://github.com/AnalyticalGraphicsInc/3d-tiles) format
- [ ] Global DEMs combined with local, higher resolution DEMs

## Client features
Features which will improve the client, in terms of organization, user friendliness, speed and analysis capabilities.

### Project
- [ ] Duplicate project
- [ ] Search projects
- [ ] Folders  
- [ ] Customized attribution for project/layers

### User
- [ ] Magic login link
- [ ] Magic invitation link
- [ ] Organizing of user list
- [ ] Folders

### Publish
- [ ] Publish button 
- [ ] Draft versions
- [ ] Undo/redo

### Data library
- [ ] Data library refactor
- [ ] Public data library/wiki available to all users 
- [ ] WMS layers
- [ ] Other layers (Carto, Mapbox, ESRI, databases)

### Share
- [ ] Centralized storage & ID endpoints
- [ ] Sharing of projects, data, layers across servers, users

### Draw, query
- [ ] Robust draw tool
- [ ] Double as query tool
- [ ] Create layers from draw
- [ ] Query from any shape, drawn or uploaded

## Queries
Different types of queries available to perform on data. Continuously growing list.
- [ ] Draw area and adjust `offset` of data within area
- [ ] Transect (draw line and get data along the line)
- [ ] Dip of displacement (see image below); angle of displacement vector.

## Test environment
Full test environment of all aspects of all libraries, both unit tests and full integration tests, ensuring stable production environment.

#### Server side
- [ ] Full test coverage of server side code with `integration tests`
- [ ] Test coverage with `unit tests` for relevant areas
- [ ] Continous Integration testing, run on each code push
- [ ] CI for Docker builds

#### Client side
- [ ] Test environment with Mocha/Karma
- [ ] `Integration tests` for all user interactions
- [ ] `Unit tests` for relevant areas
- [ ] Tests for dependencies
- [ ] CI for client-side tests

## Data pipeline automation
Fully autonomous import and processing of all data sources, with automatic checking of new data. 

- [ ] Pre-rendering of vector tiles on import
- [ ] Scripts for importing data automatically into cube/project/layers/datasets
- [ ] API for automatic webhooks

## Modular plugin architecture
Increase modularity of all components, making it increasingly easy to add new custom plugins, both server- and client-side.

- [ ] Refactor of client side, make more modular, event-driven
- [ ] Refactor of server-side, allowing plugins
- [ ] Refactor into client-side folder for storing plugins
- [ ] Server side plugins (instead of scripts), 
- [ ] GUI for portal; settings, config, plugins, users, everything. 

## Analytics
All kinds of analytics for understanding and documenting user interactions and, by inference, general usefulness for the public.
- [ ] API for adding webhooks, listeners
- [ ] Slack, Google Analytics integration endpoints
- [ ] Client-side analytics for all user actions
- [ ] Server-side analytics for all actions
- [ ] Analytics for CPU usage, memory, load, import times, render times, other performance metrics
- [ ] Analytics available directly in portal

## Offline mode
Ensure that user can use the portal even if without internet connection. Caching of data, and caching of updates to push to server, to be done when back online.
- [ ] Cache data in browser
- [ ] Cache background map in browser
- [ ] Queue updates to server
- [ ] Push updates when back online

**Comment by knutole** [comment]
## Other features to discuss
![pasted image at 2016_11_21 11_28 pm](https://cloud.githubusercontent.com/assets/2197944/20506409/266b77dc-b054-11e6-9b02-3f79027ef901.png)

**Comment by knutole** [comment]
## Meeting with John
- [ ] Show 3D
- [ ] script for change_password.js


### Discussion
- [ ] SBAS - pixels are not true representation of coverage anyway (due to sat angle vs UTM), so perhaps better to just show as points anyway.
- [ ] WMS. List of predefined layer + option to add own for advanced users. Queries. Custom queries specific to the data (same fn as imported data).
- [ ] PostGIS is good
- [ ] Label on a point (chosen from a field)
- [ ] Don't need to pull data from ArcGIS db or Oracle.
- [ ] Attribution to data layers
- [ ] Download of data is not necessary in this project (screenshot is sufficient)

**Comment by knutole** [comment]
# Priorities

## Milestone 1: 15th May
NGU wants to open the portal to the public in May/June. Area: Tromø, Bergen, Oslo, Trondheim + west-coast of Norway. All `Radarsat` data. Total perhaps 100M points.

Scaling issues must be addressed before this, obviously. This means vector tiles + scalability points must be done.

#### Priorities
1. Vector tiles
2. Scalability
3. Hooks for processing when new data is added in PostGIS
4. Attribution
4. WMS, list of available layers; include own; searchable database of layers; etc.
5. `float32` support
---
5. Improvements to InSAR chart
6. Dynamic layer menu
7. Queries: re-referencing; `offset of mvel`.
8. Metadata in info box
9. Scaling on smaller screens
10. Labels on point

## Milestone 2, end of 2017. 
Points up to 6 should be done by end of 2017.

## Milestone 3, sometime in 2018.
- [ ] 3D support
